"""Whole Body Tracking command presets for the AgiBot X2 robot."""

import os
from dataclasses import replace
from pathlib import Path

from holosoma.config_types.command import CommandManagerCfg, CommandTermCfg, MotionConfig, NoiseToInitialPoseConfig

# Resolved from this file so the checkout works at any path; X2_MOTION_DIR overrides.
_MOTION_ROOT = Path(__file__).resolve().parents[3] / "data" / "motions" / "x2_31dof"
_BOX_MULTISPEED = os.environ.get(
    "X2_MOTION_DIR", str(_MOTION_ROOT / "whole_body_tracking" / "box_multispeed")
)

# v11 (post hardware trial): dof_pos noise raised 0.1 -> 0.15 rad. On the real
# robot the ramp-to-start pose is imperfect (encoder offsets, gravity sag), and
# the policy fell as soon as the bend started from a slightly-off pose. Training
# must cover that error band, not just +/-0.1 rad around the reference.
#
# v26 (post hardware trial 2): dof_pos noise raised 0.15 -> 0.30 rad and root
# xy noise 0.05 -> 0.10 m. On hardware the operator's initial FOOT STANCE
# varies (gap between the feet, fore-aft offset); planted feet cannot slide on
# a real floor, so a stance mismatch is a PERSISTENT offset for the whole
# motion, not a transient. +/-0.30 rad on hip roll/yaw at reset spawns stances
# from ~5 cm to ~50 cm wide, teaching the policy to funnel a wide band of feet
# configurations into the pickup instead of fighting them. Box xy noise also
# raised 0.05 -> 0.08 m (blind policy: stance error shifts hand-box geometry).
# v28 (final pre-demo robustification): dof_pos 0.30 -> 0.40 rad, root xy
# 0.10 -> 0.12 m, box xy 0.08 -> 0.10 m. Covers an even wider band of operator
# stances -- feet gap, fore-aft offset, toe-in/out -- so the policy funnels
# whatever stance it wakes up in into the pickup without repositioning feet.
# v29: dof_pos 0.40 -> 0.50 rad, explicitly targeting leg-stance robustness:
# the policy must funnel an even wider band of hip/knee/ankle configurations
# into the squat instead of assuming the training-default leg placement.
init_pose_config = NoiseToInitialPoseConfig(
    overall_noise_scale=1.0,
    dof_pos=0.50,
    root_pos=[0.12, 0.12, 0.03],
    root_rot=[0.1, 0.1, 0.2],
    root_lin_vel=[0.5, 0.5, 0.2],
    root_ang_vel=[0.52, 0.52, 0.78],
    object_pos=[0.10, 0.10, 0.0],
)

# Bodies tracked against the reference motion. Ankles stay in the list so the
# critic observation dim matches warm-started checkpoints; v27 stops *killing*
# episodes for ankle drift (termination.py) and adds an explicit foot-slip
# penalty so the policy is no longer rewarded for skating feet in sim.
X2_BODY_NAMES_TO_TRACK = [
    "pelvis",
    "left_hip_roll_link",
    "left_knee_link",
    "left_ankle_roll_link",
    "right_hip_roll_link",
    "right_knee_link",
    "right_ankle_roll_link",
    "torso_link",
    "left_shoulder_roll_link",
    "left_elbow_link",
    "left_wrist_roll_link",
    "right_shoulder_roll_link",
    "right_elbow_link",
    "right_wrist_roll_link",
]

# Sampling structure: the adaptive sampler focuses on the failure-heavy grasp
# moment, but is capped by a 30% uniform floor. start_at_timestep_zero_prob was
# raised 0.15 -> 0.35 for v11: on hardware the failure was the standing-start
# bend, which is exactly the phase that only t=0 episodes exercise end-to-end
# (mid-motion starts spawn the robot already bent with the box at reference).
# v26: raised further 0.35 -> 0.5 -- stance-variation robustness is learned
# almost entirely in t=0 episodes (settle from a randomized stance, then bend).
# v28: 0.55 -> 0.65 -- deployment always starts at t=0; the standing-start
# bend and the stand-up-with-box are exactly what t=0 episodes exercise.
motion_config = MotionConfig(
    motion_file="holosoma/data/motions/x2_31dof/whole_body_tracking/sub3_largebox_003_mj.npz",
    body_names_to_track=X2_BODY_NAMES_TO_TRACK,
    body_name_ref=["torso_link"],
    use_adaptive_timesteps_sampler=True,
    adaptive_uniform_ratio=0.3,
    start_at_timestep_zero_prob=0.65,
    noise_to_initial_pose=init_pose_config,
)

# v29: train on THREE playback speeds of the pickup (0.8x / 1.0x / 1.25x,
# generated by box_pickup/make_speed_variants.py). The slow variant holds the
# squat and the grip under load ~25% longer; the fast one demands a more
# dynamic lift. One policy covers all three, so deployment can feed whichever
# reference speed suits the demo. freeze_at_timestep_zero (p=0.9 per step,
# ~0.2 s expected hold with an exponential tail) makes t=0 episodes practice
# STABILIZING the upright start pose from a noisy stance before the bend --
# the exact state the robot is in while the operator holds it pre-engage and
# again after the stand-up.
#
# v32 HOLD FOCUS: biased mid-motion (hold/set-down). That starved the
# standing-start squat that IRL always runs -- and is where v31 dies.
#
# v33 WAIST FIX: restore heavy t=0 sampling so every episode practices the
# upright -> bend that deploy uses. Keep multispeed motions + mild freeze so
# the robot still learns to stabilize before bending. Hold/set-down remain
# reachable via longer episodes and the adaptive sampler.
motion_config_w_object = replace(
    motion_config,
    motion_dir=_BOX_MULTISPEED,
    start_at_timestep_zero_prob=0.70,
    adaptive_uniform_ratio=0.20,
    freeze_at_timestep_zero_prob=0.5,
)

x2_31dof_wbt_command = CommandManagerCfg(
    params={},
    setup_terms={
        "motion_command": CommandTermCfg(
            func="holosoma.managers.command.terms.wbt:MotionCommand",
            params={
                "motion_config": motion_config,
            },
        ),
    },
    reset_terms={
        "motion_command": CommandTermCfg(
            func="holosoma.managers.command.terms.wbt:MotionCommand",
        )
    },
    step_terms={
        "motion_command": CommandTermCfg(
            func="holosoma.managers.command.terms.wbt:MotionCommand",
        )
    },
)

x2_31dof_wbt_command_w_object = replace(
    x2_31dof_wbt_command,
    setup_terms={
        "motion_command": CommandTermCfg(
            func="holosoma.managers.command.terms.wbt:MotionCommand",
            params={
                "motion_config": motion_config_w_object,
            },
        )
    },
)

# Crawl: much smaller init noise than the box suite (0.5 rad dof / 0.12 m
# root). Prone resets with huge stance noise spawn self-penetrating limbs and
# teach the policy to thrash rather than track the crawl. Mild noise still
# covers sim2real pose error.
crawl_init_pose_config = NoiseToInitialPoseConfig(
    overall_noise_scale=1.0,
    dof_pos=0.10,
    root_pos=[0.05, 0.05, 0.02],
    root_rot=[0.05, 0.05, 0.10],
    root_lin_vel=[0.2, 0.2, 0.1],
    root_ang_vel=[0.3, 0.3, 0.3],
    object_pos=[0.0, 0.0, 0.0],
)

# v5: deploy ALWAYS starts at t=0 and must crawl the full slope. Single
# palmflat motion (no standup pack — v6 multi-clip training regressed the
# climb). Heavy t=0 + healthy uniform floor.
motion_config_crawl = replace(
    motion_config,
    motion_file=(
        "holosoma/data/motions/x2_31dof/whole_body_tracking/crawl_slope_palmflat_mj.npz"
    ),
    motion_dir="",
    noise_to_initial_pose=crawl_init_pose_config,
    start_at_timestep_zero_prob=0.70,
    adaptive_uniform_ratio=0.30,
    freeze_at_timestep_zero_prob=0.0,
    enable_default_pose_append=False,
)

x2_31dof_wbt_crawl_command = replace(
    x2_31dof_wbt_command,
    setup_terms={
        "motion_command": CommandTermCfg(
            func="holosoma.managers.command.terms.wbt:MotionCommand",
            params={
                "motion_config": motion_config_crawl,
            },
        )
    },
)

__all__ = [
    "x2_31dof_wbt_command",
    "x2_31dof_wbt_command_w_object",
    "x2_31dof_wbt_crawl_command",
]
